on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }} , ghcr.io/${{ github.repository }}:${{github.ref_name}} , ghcr.io/${{ github.repository }}:cache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-to: type=inline,mode=max

      - name: Create release
        uses: "actions/github-script@v7.0.1"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const tag = context.payload.ref.replace(/\/refs\/tags\//, '')
            try {
              await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                draft: false,
                generate_release_notes: true,
                prerelease: false,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
